---
title: "Coding with Python"
subtitle: "R Version"
author: "Wendy Liang"
date: "February 13, 2019"
output: html_document
---

## Part 3 - Conditionals

### Task 10

```{r}
num <- sample(1:100, 1)
if (num <= 25) {
  print("1st Quartile")
} else if (num > 25 & num <= 50) {
  print("2nd Quartile")
} else if (num > 50 & num <= 75) {
  print("3rd Quartile")
} else {
  print("4th Quartile")
}

```

## Part 4 - Loops

### Task 11

```{r}
cities <- list("Seattle", "Kent", "Bellevue",
               "Bothell", "Renton", "Tacoma")
for (city in cities) {
  print(paste0("Warning, residents of ", city, 
               ", temperatures will reach sub-zero temperatures today, please stay indoors if possible."))
}
```

### Task 12

```{r}
states <- list("Washington", "California", "Nevada", "Idaho",
               "Montana", "Utah", "Colorado", "New Mexico")
paths <- list()
for (state in states) {
  paths[[state]] <- paste0("U://Users/Zhang/Geog_458/", state, ".shp")
  print(paths[[state]])
}
```

### Task 13

```{r}
i <- 10
while (i >= 0) {
  print(paste0("T-minus ", i))
  i <- i - 1
}
```

## Part 5 - Functions

### Task 14

```{r}
countdown <- function(j) {
  while (j >= 0) {
    print(paste0("T-minus ", j))
    j <- j - 1
  }
}
```

### Task 15

```{r}
quartile_calc <- function(j) {
  if (j >= 0 & j <= 25) {
    print("1st Quartile")
  } else if (j > 25 & j <= 50) {
    print("2nd Quartile")
  } else if (j > 50 & j <= 75) {
    print("3rd Quartile")
  } else if (j > 75 & j <= 100) {
    print("4th Quartile")
  } else {
    print("Error")
  }
}
```